import React from 'react'
import "../styles/experience.css"
import '../styles/global.css';
export default function Experience() {
  return (
    <section className="experience-section">
      <h6 className="experience-title">My professional<br />experience<div className="special-circle"></div>
</h6>
      <div className="experience-content">
        <div className="experience-content-section">
          <h2>Mobile Developer</h2>
          <p>Easy-relay, 2022</p>
          <h5 className="experience-technologies">Technologies used</h5>
          <h5>Flutter, Dart, BloC pattern, Firebase, PHP</h5>
          <p>I designed and built a mobile order delivery application, that’s available<br/>in all Algeria’s states. This application is mainly based on Flutter and PHP.<br/>I created the interfaces and animations using Flutter and I manipulated<br/>the state management using the BloC pattern. With PHP, I added endpoints to the existing API.</p>
        </div>
        <div className="experience-content-section">
          <h2>Back-end developer</h2>
          <p>Brainiac, 2020</p>
          <h5 className="experience-technologies">Technologies used</h5>
          <h5>Flutter, Dart, BloC pattern, Firebase, PHP</h5>
          <p>I developed a REST API using ExpressJS and NodeJS . The API<br/>was used to get data from database, consume this data in the application<br/>through an artificial intelligence model, and update the database<br/>whenever a new data is generated by the model.</p>
        </div>
      </div>

    </section>
  )
}
